"""empty message

Revision ID: 2b1890817c22
Revises: e79d45fb58f7
Create Date: 2017-04-02 22:58:54.521255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b1890817c22'
down_revision = 'e79d45fb58f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('age', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('sex', sa.String(length=2), nullable=False))
    op.drop_column('user', '地址')
    op.drop_column('user', '姓名')
    op.drop_column('user', '性别')
    op.drop_column('user', '年龄')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('年龄', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('性别', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('user', sa.Column('姓名', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('user', sa.Column('地址', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('user', 'sex')
    op.drop_column('user', 'name')
    op.drop_column('user', 'age')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
